### ISSUE TITLE
Port closes after 1 rest connection.

### ISSUE THREAD

**Issue by judders** [IOT-DSA/dslink-dart-rest#8]
Hello.

I have set up a Rest server value through he dataflow. 
When using chrome to view the point it works the 1st time and never again. 
http://[ipaddres]:8020/Temp_Office?value 
Checking port 8020 I find the port is open before the 1st connection, and then closes.
Re-installing the rest link makes no difference. Firewall is disable.

**Comment by kubeliv** [comment]
@judders PR #9 will fix this issue.

**Comment by judders** [comment]
Thank you Logan. Much appreciated .
